import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MyCarousel from "../components/UI/carousel";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to CodeSpace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">CoderSpace!</a>
        </h1>
        <MyCarousel />
      </main>
    </div>
  );
}
