import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to CodeSpace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">CoderSpace!</a>
        </h1>

        <p className={styles.description}>
          Get started by creating your account{" "}
          <code className={styles.code}>Hello World!</code>
        </p>

        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>Login &rarr;</h2>
            <p>Login to continue using this app and manage your workspace</p>
          </a>

          <a href="" className={styles.card}>
            <h2>Signup &rarr;</h2>
            <p>
              Signup to create your profile and explore what features we have!
            </p>
          </a>

          <a href="" className={styles.card}>
            <h2>Compile and Run &rarr;</h2>
            <p>
              Use our compiler to compile and run your code in any language.
            </p>
          </a>

          <a href="" className={styles.card}>
            <h2>Upload Files&rarr;</h2>
            <p>
              Upload all your files to keep them at one place, using our cloud
              storage.
            </p>
          </a>
        </div>
      </main>
    </div>
  );
}
